<?php

namespace Unit\Models;

use App\Config\Database;
use App\Models\Category;
use PHPUnit\Framework\TestCase;

class CategoryTest extends TestCase
{
    private $db;
    private $category;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->db = Database::getInstance();
        $this->db->exec("SET FOREIGN_KEY_CHECKS = 0");
        $this->db->exec("TRUNCATE TABLE post_category");
        $this->db->exec("TRUNCATE TABLE posts");
        $this->db->exec("TRUNCATE TABLE categories");
        $this->db->exec("SET FOREIGN_KEY_CHECKS = 1");

        $this->category = new Category();
    }

    public function testCanCreateCategory() :void
    {
        $this->category->title = 'Тестовая категория';
        $this->category->description = 'Описание тестовой категории';

        $result = $this->category->save();

        $this->assertTrue($result);
        $this->assertNotNull($this->category->id);
    }

    public function testCanFindCategoryById(){
        $this->category->title = 'Для поиска';
        $this->category->description = 'Описание тестовой категории';
        $this->category->save();
        $id = $this->category->id;

        $found = new Category();
        $found->find($id);

        $this->assertEquals('Для поиска', $found->title);
    }
}