<?php

namespace Unit\Models;

use App\Config\Database;
use App\Models\Category;
use PHPUnit\Framework\TestCase;

class CategoryTest extends TestCase
{
    private $db;
    private $category;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->db = Database::getInstance();
        $this->db->exec("SET FOREIGN_KEY_CHECKS = 0");
        $this->db->exec("TRUNCATE TABLE post_category");
        $this->db->exec("TRUNCATE TABLE posts");
        $this->db->exec("TRUNCATE TABLE categories");
        $this->db->exec("SET FOREIGN_KEY_CHECKS = 1");

        $this->category = new Category();
    }
}