<?php

namespace Models;

use App\Config\Database;
use App\Models\Post;
use PHPUnit\Framework\TestCase;

class PostTest extends TestCase
{
    private $db;
    private $post;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->db = Database::getInstance();
        $this->db->exec("SET FOREIGN_KEY_CHECKS = 0");
        $this->db->exec("TRUNCATE TABLE post_category");
        $this->db->exec("TRUNCATE TABLE posts");
        $this->db->exec("TRUNCATE TABLE categories");
        $this->db->exec("SET FOREIGN_KEY_CHECKS = 1");

        $this->post = new Post();
    }

    public function testCanCreatePost() :void
    {
        $this->post->title = 'Тестовый пост';
        $this->post->description = 'Тестовый пост - описание';

        $result = $this->post->save();

        $this->assertTrue($result);
        $this->assertNotNull($this->post->id);
    }
}